# Generated by Django 4.2.11 on 2024-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrientFact',
            fields=[
                ('id', models.AutoField(help_text='번호', primary_key=True, serialize=False)),
                ('food_cd', models.CharField(help_text='식품코드', max_length=8)),
                ('group_name', models.CharField(help_text='식품군', max_length=20)),
                ('food_name', models.CharField(help_text='식품이름', max_length=100)),
                ('research_year', models.CharField(help_text='조사년도', max_length=4)),
                ('maker_name', models.CharField(help_text='지역/제조사', max_length=100)),
                ('ref_name', models.CharField(help_text='자료출처', max_length=100)),
                ('serving_size', models.FloatField(help_text='1회 제공량')),
                ('calorie', models.FloatField(help_text='열량(kcal)(1회제공량당)')),
                ('carbohydrate', models.FloatField(help_text='탄수화물(g)(1회제공량당)')),
                ('protein', models.FloatField(help_text='단백질(g)(1회제공량당)')),
                ('province', models.FloatField(help_text='지방(g)(1회제공량당)')),
                ('sugars', models.FloatField(help_text='총당류(g)(1회제공량당)')),
                ('salt', models.FloatField(help_text='나트륨(mg)(1회제공량당)')),
                ('cholesterol', models.FloatField(help_text='콜레스테롤(mg)(1회제공량당)')),
                ('saturated_fatty_acids', models.FloatField(help_text='포화지방산(g)(1회제공량당)')),
                ('trans_fat', models.FloatField(help_text='트랜스지방(g)(1회제공량당)')),
            ],
        ),
    ]
