# Generated by Django 4.2.11 on 2024-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrients", "0002_alter_foodnutrientfact_calorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodnutrientfact",
            name="food_cd",
            field=models.CharField(db_index=True, help_text="식품코드", max_length=8),
        ),
        migrations.AlterField(
            model_name="foodnutrientfact",
            name="food_name",
            field=models.CharField(db_index=True, help_text="식품이름", max_length=100),
        ),
        migrations.AlterField(
            model_name="foodnutrientfact",
            name="maker_name",
            field=models.CharField(
                db_index=True, help_text="지역/제조사", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="foodnutrientfact",
            name="research_year",
            field=models.CharField(db_index=True, help_text="조사년도", max_length=4),
        ),
    ]
